# Generated by Django 4.2.6 on 2023-10-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_feild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('title2', models.CharField(max_length=100, null=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('idea', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
